T28: Contributes to documentation
ixpantia/ixplorer pull request #89
Opened 2022-01-14 19:23 UTC by danielgranadoscampos

- Adds english translated vignettes closing #15 
- Adds new sections to vignettes about authentication workflow and sections about the new functions to contribute to #28 
- Closes #41 
- Adds translated versions of functions add_upstream() and set_git_timeout()
- Adds keyring structure to add_upstream()
- Adds to new images about the authentication gadget 
- Adds new section to readme contributing to #85

2022-01-14 20:47 UTC, andreavargasmon requested changes

2022-01-14 20:47 UTC, andreavargasmon commented on R/git.R
> +fijar_pausa_git <- function(pausa =  14000, global = FALSE) {
le pondría un nombre ligeramente distinto:

`fijar_tiempo_credenciales` por ejemplo. Porque "pausa_git" suena como que vamos a poner en pausa git

2022-01-17 17:20 UTC, ronnyhdez commented on R/git.R
> +incluye_upstream <- function(instancia = "guardada"){
Faltan espacios entre ")" y "{"

2022-01-17 17:20 UTC, ronnyhdez commented on R/git.R
> +#' @description Esta es una traducida que llama a set_git_timeout().
Supongo que aquí va "esta es una función traducida"

2022-01-17 17:20 UTC, ronnyhdez commented on R/git.R
> +#' común sería (en una máquina Linux) <git credential.helper store>. Sin
Creo que esto no es únicamente una máquina Linux. Porque se puede hacer desde la terminal de RStudio, pero no estoy seguro cómo funcionaría en macOS o en windows

2022-01-17 17:20 UTC, ronnyhdez commented on R/sync_branch.R
> +actualizar_rama <- function(){
Esto supongo que es una función en construcción o bien hay que validar si no se quedó código fuera del commit

2022-01-17 17:20 UTC, ronnyhdez commented on README.Rmd
> +El paquete ixplorer trae la funcionalidad de ixplorer mas cerca tuyo. Tiene el propósito de permitir trabajar más agilmente con su equipo de datos desde Rstudio
Rstudio debe de ser RStudio

2022-01-18 17:37 UTC, andreavargasmon approved these changes

2022-01-18 17:54 UTC, merged